### ISSUE TITLE
endpointId: 0B

### ISSUE THREAD

**Issue by GiacomoST** [obmaz/smartthings_edge_driver#1]
You could adapt your driver to work with this 2 gang switch.

application: 01
endpointId: 0B
firmwareFullVersion: 00000001
firmwareImageType: 0
firmwareManufacturerCode: 4478
manufacturer: 3A Smart Home DE
model: LXN-2S27LX1.0
onOff: catchall
zigbeeNodeType: ROUTER
Raw Description 0B C05E 0000 01 07 0000 0004 0003 0006 0005 1000 0008 01 0019.

Thanks

**Comment by obmaz** [comment]
I added it to fingerprint. but I'm not sure whether it works due to endpointid

If you can use the cli, it would be helpful to give the log (like below) of when you turn on/off the switchs.

<ZigbeeDevice: 56491210-e0a9-4aff-827c-2449984e5f81 [0xAB70] (bedroom light)> received Zigbee message: < ZigbeeMessageRx || type: 0x00, < AddressHeader || src_addr: 0xAB70, src
_endpoint: 0x01, dest_addr: 0x0000, dest_endpoint: 0x01, profile: 0x0104, cluster: OnOff >, lqi: 0xFF, rssi: -44, body_length: 0x0008, < ZCLMessageBody || < ZCLHeader || frame_ctrl: 0x18, seqno: 0x19, ZCLCommandId: 0x01 >, < ReadAttr
ibuteReponse || < AttributeRecord || AttributeId: 0x0000, ZclStatus: SUCCESS, DataType: Boolean, OnOff: false > > > >

**Comment by GiacomoST** [comment]
Good morning
The logic works but the two switches don't switch. It sees the status of the two switches.
As soon as I get home, if you have time, I will send you the Cli reports. Thanks for your help. The 3 gang swicth of the same brand but with endpoint 1 worksInviato dal mio Galaxy
-------- Messaggio originale --------Da: obmaz ***@***.***> Data: 15/10/21  09:58  (GMT+01:00) A: obmaz/smartthings_edge_driver ***@***.***> Cc: GiacomoST ***@***.***>, Author ***@***.***> Oggetto: Re: [obmaz/smartthings_edge_driver] endpointId: 0B (#1) 
I added it to fingerprint. but I'm not sure whether it works due to endpointid
If you can use the cli, it would be helpful to give the log (like below) of when you turn on/off the switchs.
<ZigbeeDevice: 56491210-e0a9-4aff-827c-2449984e5f81 [0xAB70] (bedroom light)> received Zigbee message: < ZigbeeMessageRx || type: 0x00, < AddressHeader || src_addr: 0xAB70, src
_endpoint: 0x01, dest_addr: 0x0000, dest_endpoint: 0x01, profile: 0x0104, cluster: OnOff >, lqi: 0xFF, rssi: -44, body_length: 0x0008, < ZCLMessageBody || < ZCLHeader || frame_ctrl: 0x18, seqno: 0x19, ZCLCommandId: 0x01 >, < ReadAttr
ibuteReponse || < AttributeRecord || AttributeId: 0x0000, ZclStatus: SUCCESS, DataType: Boolean, OnOff: false > > > >

**Comment by GiacomoST** [comment]
From the Smartthings interface : Key Main ON : 2021-10-19T17:10:46.171141604+00:00 TRACE zigbee-tuya-switch  Received event with handler capability2021-10-19T17:10:46.181858604+00:00 INFO zigbee-tuya-switch  <ZigbeeDevice: a1fc1da6-8daa-45fa-abae-9866f3f7b34b [0x04BA] (Luce Bagno giorno)> received command: {"command":"on","capability":"switch","args":[],"positional_args":[],"component":"main"}2021-10-19T17:10:46.188772937+00:00 INFO zigbee-tuya-switch  <<---- Moon ---->> is_one_switch : false2021-10-19T17:10:46.194729271+00:00 INFO zigbee-tuya-switch  <<---- Moon ---->> is_multi_switch : false2021-10-19T17:10:46.201133937+00:00 INFO zigbee-tuya-switch  <<---- Moon ---->> is_one_switch : false2021-10-19T17:10:46.207142937+00:00 INFO zigbee-tuya-switch  <<---- Moon ---->> is_multi_switch : false2021-10-19T17:10:46.213646604+00:00 TRACE zigbee-tuya-switch  Found CapabilityCommandDispatcher handler in zigbee-tuya-switch2021-10-19T17:10:46.227123937+00:00 DEBUG zigbee-tuya-switch  Luce Bagno giorno device thread event handled2021-10-19T17:10:46.552619937+00:00 TRACE zigbee-tuya-switch  Received event with handler zigbee2021-10-19T17:10:46.561297271+00:00 INFO zigbee-tuya-switch  <ZigbeeDevice: a1fc1da6-8daa-45fa-abae-9866f3f7b34b [0x04BA] (Luce Bagno giorno)> received Zigbee message: < ZigbeeMessageRx || type: 0x00, < AddressHeader || src_addr: 0x04BA, src_endpoint: 0x0B, dest_addr: 0x0000, dest_endpoint: 0x01, profile: 0x0104, cluster: OnOff >, lqi: 0x6C, rssi: -73, body_length: 0x0005, < ZCLMessageBody || < ZCLHeader || frame_ctrl: 0x18, seqno: 0x7E, ZCLCommandId: 0x0B >, < DefaultResponse || cmd: 0x01, ZclStatus: SUCCESS > > >2021-10-19T17:10:46.576121937+00:00 INFO zigbee-tuya-switch  <<---- Moon ---->> is_one_switch : false2021-10-19T17:10:46.582388604+00:00 INFO zigbee-tuya-switch  <<---- Moon ---->> is_multi_switch : false2021-10-19T17:10:46.588424604+00:00 INFO zigbee-tuya-switch  <<---- Moon ---->> is_one_switch : false2021-10-19T17:10:46.594728604+00:00 INFO zigbee-tuya-switch  <<---- Moon ---->> is_multi_switch : false2021-10-19T17:10:46.601604604+00:00 TRACE zigbee-tuya-switch  Found ZigbeeMessageDispatcher handler in zigbee-tuya-switch2021-10-19T17:10:46.607353604+00:00 INFO zigbee-tuya-switch  Executing ZclGlobalCommandHandler: cluster: OnOff, command: DefaultResponse2021-10-19T17:10:46.614586604+00:00 INFO zigbee-tuya-switch  <ZigbeeDevice: a1fc1da6-8daa-45fa-abae-9866f3f7b34b [0x04BA] (Luce Bagno giorno)> emitting event: {"capability_id":"switch","state":{"value":"on"},"attribute_id":"switch","component_id":"main"}2021-10-19T17:10:46.673633937+00:00 DEBUG zigbee-tuya-switch  Luce Bagno giorno device thread event handled2021-10-19T17:10:47.343070937+00:00 TRACE zigbee-tuya-switch  Received event with handler zigbee2021-10-19T17:10:47.354407271+00:00 INFO zigbee-tuya-switch  <ZigbeeDevice: a1fc1da6-8daa-45fa-abae-9866f3f7b34b [0x04BA] (Luce Bagno giorno)> received Zigbee message: < ZigbeeMessageRx || type: 0x00, < AddressHeader || src_addr: 0x04BA, src_endpoint: 0x0B, dest_addr: 0x0000, dest_endpoint: 0x01, profile: 0x0104, cluster: OnOff >, lqi: 0x78, rssi: -70, body_length: 0x0007, < ZCLMessageBody || < ZCLHeader || frame_ctrl: 0x08, seqno: 0x4B, ZCLCommandId: 0x0A >, < ReportAttribute || < AttributeRecord || AttributeId: 0x0000, DataType: Boolean, OnOff: true > > > >2021-10-19T17:10:47.371589604+00:00 INFO zigbee-tuya-switch  <<---- Moon ---->> is_one_switch : false2021-10-19T17:10:47.380593271+00:00 INFO zigbee-tuya-switch  <<---- Moon ---->> is_multi_switch : false2021-10-19T17:10:47.386847937+00:00 INFO zigbee-tuya-switch  <<---- Moon ---->> is_one_switch : false2021-10-19T17:10:47.393304604+00:00 INFO zigbee-tuya-switch  <<---- Moon ---->> is_multi_switch : false2021-10-19T17:10:47.399722604+00:00 TRACE zigbee-tuya-switch  Found ZigbeeMessageDispatcher handler in zigbee-tuya-switch2021-10-19T17:10:47.405469937+00:00 INFO zigbee-tuya-switch  Executing ZclClusterAttributeValueHandler: cluster: OnOff, attribute: OnOff2021-10-19T17:10:47.412407604+00:00 INFO zigbee-tuya-switch  <ZigbeeDevice: a1fc1da6-8daa-45fa-abae-9866f3f7b34b [0x04BA] (Luce Bagno giorno)> emitting event: {"capability_id":"switch","state":{"value":"on"},"attribute_id":"switch","component_id":"main"}2021-10-19T17:10:47.427973937+00:00 DEBUG zigbee-tuya-switch  Luce Bagno giorno device thread event handledlistening for logs... | Key Main OFF : 2021-10-19T17:13:23.158298795+00:00 TRACE zigbee-tuya-switch  Received event with handler zigbee health poll2021-10-19T17:13:27.241170462+00:00 TRACE zigbee-tuya-switch  Received event with handler capability2021-10-19T17:13:27.285334462+00:00 INFO zigbee-tuya-switch  <ZigbeeDevice: a1fc1da6-8daa-45fa-abae-9866f3f7b34b [0x04BA] (Luce Bagno giorno)> received command: {"command":"off","capability":"switch","args":[],"positional_args":[],"component":"main"}2021-10-19T17:13:27.300047462+00:00 INFO zigbee-tuya-switch  <<---- Moon ---->> is_one_switch : false2021-10-19T17:13:27.309789129+00:00 INFO zigbee-tuya-switch  <<---- Moon ---->> is_multi_switch : false2021-10-19T17:13:27.321679462+00:00 INFO zigbee-tuya-switch  <<---- Moon ---->> is_one_switch : false2021-10-19T17:13:27.329683129+00:00 INFO zigbee-tuya-switch  <<---- Moon ---->> is_multi_switch : false2021-10-19T17:13:27.344541795+00:00 TRACE zigbee-tuya-switch  Found CapabilityCommandDispatcher handler in zigbee-tuya-switch2021-10-19T17:13:27.375192795+00:00 DEBUG zigbee-tuya-switch  Luce Bagno giorno device thread event handled2021-10-19T17:13:27.453372795+00:00 TRACE zigbee-tuya-switch  Received event with handler zigbee2021-10-19T17:13:27.478643462+00:00 INFO zigbee-tuya-switch  <ZigbeeDevice: a1fc1da6-8daa-45fa-abae-9866f3f7b34b [0x04BA] (Luce Bagno giorno)> received Zigbee message: < ZigbeeMessageRx || type: 0x00, < AddressHeader || src_addr: 0x04BA, src_endpoint: 0x0B, dest_addr: 0x0000, dest_endpoint: 0x01, profile: 0x0104, cluster: OnOff >, lqi: 0x70, rssi: -72, body_length: 0x0005, < ZCLMessageBody || < ZCLHeader || frame_ctrl: 0x18, seqno: 0x16, ZCLCommandId: 0x0B >, < DefaultResponse || cmd: 0x00, ZclStatus: SUCCESS > > >2021-10-19T17:13:27.502209462+00:00 INFO zigbee-tuya-switch  <<---- Moon ---->> is_one_switch : false2021-10-19T17:13:27.512822129+00:00 INFO zigbee-tuya-switch  <<---- Moon ---->> is_multi_switch : false2021-10-19T17:13:27.535370462+00:00 INFO zigbee-tuya-switch  <<---- Moon ---->> is_one_switch : false2021-10-19T17:13:27.541889795+00:00 INFO zigbee-tuya-switch  <<---- Moon ---->> is_multi_switch : false2021-10-19T17:13:27.553521462+00:00 TRACE zigbee-tuya-switch  Found ZigbeeMessageDispatcher handler in zigbee-tuya-switch2021-10-19T17:13:27.559485795+00:00 INFO zigbee-tuya-switch  Executing ZclGlobalCommandHandler: cluster: OnOff, command: DefaultResponse2021-10-19T17:13:27.572260795+00:00 INFO zigbee-tuya-switch  <ZigbeeDevice: a1fc1da6-8daa-45fa-abae-9866f3f7b34b [0x04BA] (Luce Bagno giorno)> emitting event: {"capability_id":"switch","state":{"value":"off"},"attribute_id":"switch","component_id":"main"}2021-10-19T17:13:27.646232795+00:00 DEBUG zigbee-tuya-switch  Luce Bagno giorno device thread event handled2021-10-19T17:13:28.589797795+00:00 TRACE zigbee-tuya-switch  Received event with handler zigbee2021-10-19T17:13:28.676181796+00:00 INFO zigbee-tuya-switch  <ZigbeeDevice: a1fc1da6-8daa-45fa-abae-9866f3f7b34b [0x04BA] (Luce Bagno giorno)> received Zigbee message: < ZigbeeMessageRx || type: 0x00, < AddressHeader || src_addr: 0x04BA, src_endpoint: 0x0B, dest_addr: 0x0000, dest_endpoint: 0x01, profile: 0x0104, cluster: OnOff >, lqi: 0x70, rssi: -72, body_length: 0x0007, < ZCLMessageBody || < ZCLHeader || frame_ctrl: 0x08, seqno: 0xEF, ZCLCommandId: 0x0A >, < ReportAttribute || < AttributeRecord || AttributeId: 0x0000, DataType: Boolean, OnOff: false > > > >2021-10-19T17:13:28.779602462+00:00 INFO zigbee-tuya-switch  <<---- Moon ---->> is_one_switch : false2021-10-19T17:13:28.796123796+00:00 INFO zigbee-tuya-switch  <<---- Moon ---->> is_multi_switch : false2021-10-19T17:13:28.865286462+00:00 INFO zigbee-tuya-switch  <<---- Moon ---->> is_one_switch : false2021-10-19T17:13:28.897106129+00:00 INFO zigbee-tuya-switch  <<---- Moon ---->> is_multi_switch : false2021-10-19T17:13:28.903481129+00:00 TRACE zigbee-tuya-switch  Found ZigbeeMessageDispatcher handler in zigbee-tuya-switch2021-10-19T17:13:28.954766462+00:00 INFO zigbee-tuya-switch  Executing ZclClusterAttributeValueHandler: cluster: OnOff, attribute: OnOff2021-10-19T17:13:28.962214129+00:00 INFO zigbee-tuya-switch  <ZigbeeDevice: a1fc1da6-8daa-45fa-abae-9866f3f7b34b [0x04BA] (Luce Bagno giorno)> emitting event: {"capability_id":"switch","state":{"value":"off"},"attribute_id":"switch","component_id":"main"}2021-10-19T17:13:29.021459796+00:00 DEBUG zigbee-tuya-switch  Luce Bagno giorno device thread event handledlistening for logs... – Key 1 ON : 2021-10-19T17:14:50.764749139+00:00 TRACE zigbee-tuya-switch  Received event with handler capability2021-10-19T17:14:50.775573805+00:00 INFO zigbee-tuya-switch  <ZigbeeDevice: a1fc1da6-8daa-45fa-abae-9866f3f7b34b [0x04BA] (Luce Bagno giorno)> received command: {"command":"on","capability":"switch","args":[],"positional_args":[],"component":"switch1"}2021-10-19T17:14:50.781990472+00:00 INFO zigbee-tuya-switch  <<---- Moon ---->> is_one_switch : false2021-10-19T17:14:50.788533805+00:00 INFO zigbee-tuya-switch  <<---- Moon ---->> is_multi_switch : false2021-10-19T17:14:50.794580139+00:00 INFO zigbee-tuya-switch  <<---- Moon ---->> is_one_switch : false2021-10-19T17:14:50.801174472+00:00 INFO zigbee-tuya-switch  <<---- Moon ---->> is_multi_switch : false2021-10-19T17:14:50.808160139+00:00 TRACE zigbee-tuya-switch  Found CapabilityCommandDispatcher handler in zigbee-tuya-switch2021-10-19T17:14:50.828968472+00:00 DEBUG zigbee-tuya-switch  Luce Bagno giorno device thread event handled2021-10-19T17:14:50.973077472+00:00 TRACE zigbee-tuya-switch  Received event with handler zigbee2021-10-19T17:14:50.981812139+00:00 INFO zigbee-tuya-switch  <ZigbeeDevice: a1fc1da6-8daa-45fa-abae-9866f3f7b34b [0x04BA] (Luce Bagno giorno)> received Zigbee message: < ZigbeeMessageRx || type: 0x00, < AddressHeader || src_addr: 0x04BA, src_endpoint: 0x0B, dest_addr: 0x0000, dest_endpoint: 0x01, profile: 0x0104, cluster: OnOff >, lqi: 0x70, rssi: -72, body_length: 0x0005, < ZCLMessageBody || < ZCLHeader || frame_ctrl: 0x18, seqno: 0x26, ZCLCommandId: 0x0B >, < DefaultResponse || cmd: 0x01, ZclStatus: SUCCESS > > >2021-10-19T17:14:50.996810139+00:00 INFO zigbee-tuya-switch  <<---- Moon ---->> is_one_switch : false2021-10-19T17:14:51.002779139+00:00 INFO zigbee-tuya-switch  <<---- Moon ---->> is_multi_switch : false2021-10-19T17:14:51.008962139+00:00 INFO zigbee-tuya-switch  <<---- Moon ---->> is_one_switch : false2021-10-19T17:14:51.015407805+00:00 INFO zigbee-tuya-switch  <<---- Moon ---->> is_multi_switch : false2021-10-19T17:14:51.022089805+00:00 TRACE zigbee-tuya-switch  Found ZigbeeMessageDispatcher handler in zigbee-tuya-switch2021-10-19T17:14:51.027464472+00:00 INFO zigbee-tuya-switch  Executing ZclGlobalCommandHandler: cluster: OnOff, command: DefaultResponse2021-10-19T17:14:51.034598139+00:00 INFO zigbee-tuya-switch  <ZigbeeDevice: a1fc1da6-8daa-45fa-abae-9866f3f7b34b [0x04BA] (Luce Bagno giorno)> emitting event: {"capability_id":"switch","state":{"value":"on"},"attribute_id":"switch","component_id":"main"}2021-10-19T17:14:51.096593805+00:00 DEBUG zigbee-tuya-switch  Luce Bagno giorno device thread event handled2021-10-19T17:14:51.363427139+00:00 TRACE zigbee-tuya-switch  Received event with handler zigbee2021-10-19T17:14:51.374022472+00:00 INFO zigbee-tuya-switch  <ZigbeeDevice: a1fc1da6-8daa-45fa-abae-9866f3f7b34b [0x04BA] (Luce Bagno giorno)> received Zigbee message: < ZigbeeMessageRx || type: 0x00, < AddressHeader || src_addr: 0x04BA, src_endpoint: 0x0B, dest_addr: 0x0000, dest_endpoint: 0x01, profile: 0x0104, cluster: OnOff >, lqi: 0x70, rssi: -72, body_length: 0x0007, < ZCLMessageBody || < ZCLHeader || frame_ctrl: 0x08, seqno: 0x43, ZCLCommandId: 0x0A >, < ReportAttribute || < AttributeRecord || AttributeId: 0x0000, DataType: Boolean, OnOff: true > > > >2021-10-19T17:14:51.390083472+00:00 INFO zigbee-tuya-switch  <<---- Moon ---->> is_one_switch : false2021-10-19T17:14:51.398667805+00:00 INFO zigbee-tuya-switch  <<---- Moon ---->> is_multi_switch : false2021-10-19T17:14:51.405675472+00:00 INFO zigbee-tuya-switch  <<---- Moon ---->> is_one_switch : false2021-10-19T17:14:51.413104805+00:00 INFO zigbee-tuya-switch  <<---- Moon ---->> is_multi_switch : false2021-10-19T17:14:51.419997472+00:00 TRACE zigbee-tuya-switch  Found ZigbeeMessageDispatcher handler in zigbee-tuya-switch2021-10-19T17:14:51.426090805+00:00 INFO zigbee-tuya-switch  Executing ZclClusterAttributeValueHandler: cluster: OnOff, attribute: OnOff2021-10-19T17:14:51.432871139+00:00 INFO zigbee-tuya-switch  <ZigbeeDevice: a1fc1da6-8daa-45fa-abae-9866f3f7b34b [0x04BA] (Luce Bagno giorno)> emitting event: {"capability_id":"switch","state":{"value":"on"},"attribute_id":"switch","component_id":"main"}2021-10-19T17:14:51.448437805+00:00 DEBUG zigbee-tuya-switch  Luce Bagno giorno device thread event handledlistening for logs... / the UI key 1 turned off by itself.I tried to turn key 1 (UI) back on and it went into loop then the network error appearedI can't try it because it always goes OFF (the physical key is on)  Key 1 OFF:I can't try it because it always goes OFF (the physical key is on) Loop . Network Error  Key 2 ON : 2021-10-19T17:22:49.347403312+00:00 TRACE zigbee-tuya-switch  Received event with handler capability2021-10-19T17:22:49.379881646+00:00 INFO zigbee-tuya-switch  <ZigbeeDevice: a1fc1da6-8daa-45fa-abae-9866f3f7b34b [0x04BA] (Luce Bagno giorno)> received command: {"command":"on","capability":"switch","args":[],"positional_args":[],"component":"switch2"}2021-10-19T17:22:49.405917312+00:00 INFO zigbee-tuya-switch  <<---- Moon ---->> is_one_switch : false2021-10-19T17:22:49.434291312+00:00 INFO zigbee-tuya-switch  <<---- Moon ---->> is_multi_switch : false2021-10-19T17:22:49.479474646+00:00 INFO zigbee-tuya-switch  <<---- Moon ---->> is_one_switch : false2021-10-19T17:22:49.539737979+00:00 INFO zigbee-tuya-switch  <<---- Moon ---->> is_multi_switch : false2021-10-19T17:22:49.570286312+00:00 TRACE zigbee-tuya-switch  Found CapabilityCommandDispatcher handler in zigbee-tuya-switch2021-10-19T17:22:49.663414979+00:00 DEBUG zigbee-tuya-switch  Luce Bagno giorno device thread event handled2021-10-19T17:22:49.839560646+00:00 TRACE zigbee-tuya-switch  Received event with handler zigbee2021-10-19T17:22:49.853265646+00:00 INFO zigbee-tuya-switch  <ZigbeeDevice: a1fc1da6-8daa-45fa-abae-9866f3f7b34b [0x04BA] (Luce Bagno giorno)> received Zigbee message: < ZigbeeMessageRx || type: 0x00, < AddressHeader || src_addr: 0x04BA, src_endpoint: 0x0B, dest_addr: 0x0000, dest_endpoint: 0x01, profile: 0x0104, cluster: OnOff >, lqi: 0x7C, rssi: -69, body_length: 0x0005, < ZCLMessageBody || < ZCLHeader || frame_ctrl: 0x18, seqno: 0x64, ZCLCommandId: 0x0B >, < DefaultResponse || cmd: 0x01, ZclStatus: SUCCESS > > >2021-10-19T17:22:49.901935646+00:00 INFO zigbee-tuya-switch  <<---- Moon ---->> is_one_switch : false2021-10-19T17:22:49.920875312+00:00 INFO zigbee-tuya-switch  <<---- Moon ---->> is_multi_switch : false2021-10-19T17:22:49.941315312+00:00 INFO zigbee-tuya-switch  <<---- Moon ---->> is_one_switch : false2021-10-19T17:22:49.949701312+00:00 INFO zigbee-tuya-switch  <<---- Moon ---->> is_multi_switch : false2021-10-19T17:22:49.967079646+00:00 TRACE zigbee-tuya-switch  Found ZigbeeMessageDispatcher handler in zigbee-tuya-switch2021-10-19T17:22:49.972463312+00:00 INFO zigbee-tuya-switch  Executing ZclGlobalCommandHandler: cluster: OnOff, command: DefaultResponse2021-10-19T17:22:49.981510312+00:00 INFO zigbee-tuya-switch  <ZigbeeDevice: a1fc1da6-8daa-45fa-abae-9866f3f7b34b [0x04BA] (Luce Bagno giorno)> emitting event: {"capability_id":"switch","state":{"value":"on"},"attribute_id":"switch","component_id":"main"}2021-10-19T17:22:50.010805312+00:00 DEBUG zigbee-tuya-switch  Luce Bagno giorno device thread event handled2021-10-19T17:22:53.214092978+00:00 TRACE zigbee-tuya-switch  Received event with handler zigbee health polllistening for logs... | Network failure Key 2 OFF : I can't try it because it always goes OFF (the physical key is on). Loop . Network Error    Inviato da Posta per Windows Da: obmazInviato: martedì 19 ottobre 2021 18:19A: obmaz/smartthings_edge_driverCc: GiacomoST; AuthorOggetto: Re: [obmaz/smartthings_edge_driver] endpointId: 0B (#1) could you share the logs when click switch 1,2,3 and touch ST UI switch 1,2,3‽—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by GiacomoST** [comment]
mfr = "3A Smart Home DE", model = "LXN-3S27LX1.0", ep = 0x0BThis endpoint is 0x01 only for this LXN-2S27LX1.0 is 0x0B Inviato da Posta per Windows Da: obmazInviato: martedì 19 ottobre 2021 18:19A: obmaz/smartthings_edge_driverCc: GiacomoST; AuthorOggetto: Re: [obmaz/smartthings_edge_driver] endpointId: 0B (#1) could you share the logs when click switch 1,2,3 and touch ST UI switch 1,2,3‽—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by obmaz** [comment]
Thanks for testing.

Let me know and open the issue if it does not work again.
