### ISSUE TITLE
엣지드라이버 오작동 문제

### ISSUE THREAD

**Issue by ymin7589** [obmaz/smartthings_edge_driver#10]
안녕하세요. 얼마전에 manufacturer: _TZ3000_wu0shw0i model: TS0013 추가해주셔서 잘쓰고 있었는데 오늘 저녁에 갑자기 메인스위치만 작동이 되고 switch 1 2 3이 구름모양으로 바뀌고 작동이 안됩니다. 혹시 드라이버 수정이 있었나요?

**Comment by obmaz** [comment]
다른 부분 수정 하다가 해당 핑거프린트 부분이 삭제되어 복구 했습니다. (2022-03-25T09:48:18.265243)
