### ISSUE TITLE
main button function customizing

### ISSUE THREAD

**Issue by ymin7589** [obmaz/smartthings_edge_driver#2]
안녕하세요. 만들어주신 엣지드라이버 잘쓰고 있습니다. 이번에 st펌웨어 업데이트 이후 switch 1 2 3 도 모두 로컬자동화되는것 같네요. 자동화명 옆에 집모양이 떠서 더욱 좋아졌습니다.
main 버튼 맵핑 기능이 현재는 개별 스위치 또는 all 만 맵핑이 가능한데, 스위치 2개 복수 선택이 가능하게 변경은 안될까요?
좋은 드라이버 만들어주셔서 감사드립니다.

**Comment by obmaz** [comment]
아마도 가능할것 같습니다. 해당 기능 추가 후 게시글 업데이트 하겠습니다.

**Comment by obmaz** [comment]
해당 기능 추가 되었습니다.
한번 공개된 드라이버로 하위 호환 보장을 위해 기존 UI를 사용하는 방법으로 구현 되었습니다.
추후 프로파일 로딩을 효율적으로 할 수 있는 부분을 추가 하여 다듬을 예정입니다.
