### ISSUE TITLE
Ikeas SOMRIG shortcut button

### ISSUE THREAD

**Issue by dotanshai** [obmaz/smartthings_edge_driver#26]
Not sure if you can help, but can you please add the following to your driver:
Ikeas p/n E2213

Model : SOMRIG shortcut button
Manufacturer : IKEA of Sweden

![image](https://github.com/obmaz/smartthings_edge_driver/assets/42491156/42dec01b-069e-4ed6-af8f-927d7101ca44)

Thanks ....

**Comment by obmaz** [comment]
This edge driver does not work with ikea SOMRIG button
