### ISSUE TITLE
Can you please add the following button _TZ3000_yj6k7vfo

### ISSUE THREAD

**Issue by dotanshai** [obmaz/smartthings_edge_driver#27]
Manufacturer: TZ3000_yj6k7vfo
Model: TS0041

![image](https://github.com/obmaz/smartthings_edge_driver/assets/42491156/64d4ca45-b549-4687-9fdd-752b90787b05)

Thanks,

**Comment by obmaz** [comment]
Done (2024-01-17T01:09:52.510373885)

**Comment by dotanshai** [comment]
There is a problem with manufacturer p/n. In your driver : TZ3000_yj6k7vfo , while the actual should be : **_**TZ3000_yj6k7vfo (starting underscore is missing), can you please check ? 
Thanks....

**Comment by obmaz** [comment]
> There is a problem with manufacturer p/n. In your driver : TZ3000_yj6k7vfo , while the actual should be : _TZ3000_yj6k7vfo (starting underscore is missing), can you please check ? Thanks....

It's my mistake.
Fixed (2024-01-19T02:08:24.845871097)

**Comment by dotanshai** [comment]
After your fixing, All works. Thank you for your work  👍 😄
