### ISSUE TITLE
Can you please add Ikea RODRET Dimmer ?

### ISSUE THREAD

**Issue by dotanshai** [obmaz/smartthings_edge_driver#28]
Can you please add Ikea RODRET Dimmer here are some more details:
![image](https://github.com/obmaz/smartthings_edge_driver/assets/42491156/f9984819-b9bc-40b6-9a34-47aa045a04a2)

Another user already added this device, but didn't publish his work in a private channel. Read also here:
https://community.smartthings.com/t/post-requests-for-zigbee-edge-drivers-here-community-created/262081/1454

**Comment by obmaz** [comment]
Does this mean you want to add that finger print to the Tuya driver?

**Comment by dotanshai** [comment]
Tuya or Ikea , doesn't really matters for me. As long as the button will work.
Is that possible?

**Comment by obmaz** [comment]
I found the channel that support Ikea RODRET Dimmer. Use below channel
-  https://bestow-regional.api.smartthings.com/invite/r3Myde4gbWjp (Zigbee Button)
