### ISSUE TITLE
Konke 1버튼(추가문의)

### ISSUE THREAD

**Issue by Xinkle** [obmaz/smartthings_edge_driver#31]
https://github.com/obmaz/smartthings_edge_driver/issues/22
에서 문의드렸던 사람입니다.

혹시 제가 실제 제품을 보내드린다면 확인이 가능하실까요?(어차피 엣지드라이버 연결이 안되면 불용한 제품들이라..)

**Comment by obmaz** [comment]
본업이 바빠서 추가적인 개발은 불가능 하고, 핑거프린터 추가 정도의 작업만 가능 합니다.
