### ISSUE TITLE
can't assign your driver to my tuya zigbee button

### ISSUE THREAD

**Issue by oualibadr** [obmaz/smartthings_edge_driver#32]
Hi Obmaz,

I hope you are doing well,

I was looking for an edge driver for my tuya zigbee button when I found a post (https://community.smartthings.com/t/is-there-a-zigbee-smart-button-driver-driver/277743) on the smatthings forum mentionning that someone solved the issue by installing your drivers. so I did the same.

My problem is that I can't assign your driver to the device: I can't see it in the dropdown drivers list 

![20240423_230833](https://github.com/obmaz/smartthings_edge_driver/assets/108238436/701a0a91-f8f1-4430-ac61-0a95dc35fdf1)
![20240423_230703](https://github.com/obmaz/smartthings_edge_driver/assets/108238436/655a2616-4068-4211-bbc3-5b073db525fe)

Any idea?

Thanks,

**Comment by oualibadr** [comment]
there you go : _TZ3000_qgwcxxws

**Comment by obmaz** [comment]
I also need model number like 'TS00nn'

2024년 4월 24일 (수) 22:08, oualibadr ***@***.***>님이 작성:

**Comment by oualibadr** [comment]
here it is TS0041

**Comment by obmaz** [comment]
The FP was added and applied (2024-04-25T01:17:51.351320819)

**Comment by oualibadr** [comment]
Many Thanks !

**Comment by oualibadr** [comment]
Working like a charm :)
