### ISSUE TITLE
Please add _TZ3000_j61x9rxn

### ISSUE THREAD

**Issue by dotanshai** [obmaz/smartthings_edge_driver#33]
Hi can you please add:

Manufacturer Code: _TZ3000_j61x9rxn
Model: TS0044

![image](https://github.com/obmaz/smartthings_edge_driver/assets/42491156/6ffe30f4-6afa-4354-9270-5505bf4dc54c)

https://community.smartthings.com/t/st-edge-zigbee-driver-for-moes-4-button-scene-switch-ts004f-plus-some-smart-knob-models/237808/395

**Comment by obmaz** [comment]
Added and applied (2024-05-20T08:13:07.133693983)

**Comment by dotanshai** [comment]
All works, thanks you
