### ISSUE TITLE
shutter _TZE204_mpg22jc1

### ISSUE THREAD

**Issue by dotanshai** [obmaz/smartthings_edge_driver#34]
Hi, 
Can you please add:

```
Manufacture :_TZE204_mpg22jc1
Model : TS0601
```

![image](https://github.com/obmaz/smartthings_edge_driver/assets/42491156/17590c03-03ed-412e-b2d2-af478ce6bf9c)

Here are some more information from the manufacturer 

DP ID	Function point name	identifier	Data transfer type	type of data	Function point attributes
1	Curtain switch 1	control	Can be issued and reported（rw）	enum	enumeration value: open, stop, close
2	Percent 1	percent_control	Can be issued and reported（rw）	value	Numeric range: 0-100,
              spacing: 10, multiple: 0,
              unit: %
8	Motor steering switch 1	control_back	Can be issued and reported（rw）	enum	enumeration value: forward, back
10	Quick calibration all the way	tr_timecon	Can be issued and reported（rw）	value	Numeric range: 10-1200,
              spacing: 1, multiple: 0,
              unit: s
101	Turn on percentage status	percent_state	Report only（ro）	value	Numeric range: 0-100,
             spacing: 1, multiple: 0,
              unit: %

If your driver is not supporting shutters, can you please post in the Korean forum . The calibration feature in very important...
I know iquix
 deal with shutters, but I was unable to reach him in Github

**Comment by obmaz** [comment]
The FP is added and qpplied. (2024-05-30T04:43:05.289983744)
When I developed the EF00 cluster, I received feedback that some parts worked well and some did not.
Since I am not active in the Korean community now, it is not easy to inform iquix.

**Comment by dotanshai** [comment]
Thanks for helping...

1. Did you implemented the quick calibration in your driver ?
2. Which driver to use ? Is it zigbee-tuya-switch ?

**Comment by obmaz** [comment]
Quick Answer

1. No
2. zigbee-tuya-button
