### ISSUE TITLE
_TZ3000_ngsph3oj 핑거프린트 추가해주실수 있을까요?

### ISSUE THREAD

**Issue by umeom** [obmaz/smartthings_edge_driver#35]
Loratap 3버튼이고 한번 두번 길게누르기 지원해주는 버튼 3개있는 모델입니다

Manufacturer Code: _TZ3000_ngsph3oj
Model: TS0043 

![KakaoTalk_20240605_005723473](https://github.com/obmaz/smartthings_edge_driver/assets/171773736/976142d3-e4e2-4dbc-93f1-5fa1e7b62e23)

**Comment by obmaz** [comment]
추가 배포 하였습니다. (2024-06-07T07:09:08.7381619)

**Comment by umeom** [comment]
감사합니다
연결 잘되네용
