### ISSUE TITLE
Add driver to zemismart zigbee button 

### ISSUE THREAD

**Issue by Omer-harel** [obmaz/smartthings_edge_driver#45]
Hello,

I havee a new zemismart battery button that doesn't work properly with smarthings.

Please kindly your  help to add driver so everyone will able to use it.
I am adding picture with information.
If you need other info I would love to help.

Thank you!
![inbound6463799057956793694](https://github.com/user-attachments/assets/49205c64-c560-4b23-ab8e-f2c7452f52dd)

![inbound4540771847965572810](https://github.com/user-attachments/assets/18e6a655-c407-4a87-9543-1df7ec39c1ed)

**Comment by obmaz** [comment]
Appplied (2024-08-12T02:11:52.007821881)

**Comment by Omer-harel** [comment]
Thank you very much for your quick response.
Works perfectly!
