### ISSUE TITLE
Zigbee button 

### ISSUE THREAD

**Issue by Shaikin123** [obmaz/smartthings_edge_driver#53]
Can you please add the following zigbee button to your driver? 
![inbound7092741427470090262](https://github.com/user-attachments/assets/f397c117-605a-4cad-bade-59769808d5d4)

**Comment by dotanshai** [comment]
Dear @obmaz ,
This is the correct information sent to me by Shai U.
![image](https://github.com/user-attachments/assets/6b1bc425-de1e-4c62-9e8f-c0e0f681f0cf)

**Comment by obmaz** [comment]
Applied (2024-12-20T04:40:35.443544041 2024-12-20T04:40:35.443544041)

**Comment by Shaikin123** [comment]
Great!!! It works!!! Thanks!!!!

**Comment by Shaikin123** [comment]
Everything works great!
