### ISSUE TITLE
Zigbee-Tuya-Button - _TZ3000_xabckq1v

### ISSUE THREAD

**Issue by averagebald** [obmaz/smartthings_edge_driver#6]
application: 41
endpointId: 01
manufacturer: _TZ3000_xabckq1v
model: TS004F
zigbeeNodeType: SLEEPY_END_DEVICE

i see this added in the fingerprint but somehow it's not working. one thing i notice is its being detected as "Hejhome Smart 4 Button" when added. None of the buttons works.
![image](https://user-images.githubusercontent.com/91673397/147342870-9b286f46-ac98-42b7-b8e1-26a137b34c22.png)

**Comment by obmaz** [comment]
Yes, right. It might not work currently.
TS004F signal is not the same as TS0044.

I've ordered TS004F from aliexpress for dev.
I might start to implement it next year due to too slow delivery from ali.

I will keep this issue open and add comments when development is complete.

**Comment by averagebald** [comment]
Hi mate, 
Just want to follow up on this. Did you manage to get the TS004F? Thanks.

**Comment by obmaz** [comment]
Hi,
I stopped developing for the TS004F. The below thread below might be helpful.
- https://community.smartthings.com/t/st-edge-zigbee-driver-for-moes-4-button-scene-switch-ts004f/237808/1

**Comment by averagebald** [comment]
no worries. thanks!
