### ISSUE TITLE
zigbee-tuya-switch

### ISSUE THREAD

**Issue by GiacomoST** [obmaz/smartthings_edge_driver#7]
Good morning
After updating the Hub to version 41, the driver stopped working.

**Comment by obmaz** [comment]
@GiacomoST 
Thanks for sharing issue.
Currently, my hub version is not 41, but 40. When the update is complete, I will check it right away.
Is it possible to check if the problem happens even after re-pairing?

**Comment by obmaz** [comment]
@GiacomoST 
It has been fixed. (2022-02-02T14:59:38.851003)
