### ISSUE TITLE
제미스마트 인식 문제

### ISSUE THREAD

**Issue by ymin7589** [obmaz/smartthings_edge_driver#9]
안녕하세요
제미스마트 3갱 핑거프린트 추가해주셔서 페어링이 되었는데 메인스위치만 작동하고 스위치 1 2 3은 구름 모양으로 떠서 제어가 안되네요 무슨 문재일까요?

**Comment by obmaz** [comment]
추가 하여 배포 하였습니다.
2022-03-16T11:13:41.337402
